### ISSUE TITLE
Rename project to xk6-output-dynatrace

### ISSUE THREAD

**Issue by ppcano** [Dynatrace/xk6-output-dynatrace#1]
@henrikrexed, I suggest a project rename to follow the same convention as:

- https://github.com/grafana/xk6-output-influxdb
- https://github.com/grafana/xk6-output-prometheus-remote
- https://github.com/grafana/xk6-output-timescaledb
- https://github.com/grafana/xk6-output-kafka

**Comment by henrikrexed** [comment]
hi i rename the extensions like suggested
